# Welcome to Numpy Tutorial

In [1]:
import numpy as np


In [2]:
myarr=np.array([12,3,5,6] , np.int8)

In [3]:
myarr[0]



np.int8(12)

In [4]:
myarr.shape

(4,)

In [5]:
myarr.dtype

dtype('int8')

In [6]:
myarr[0]=45

In [7]:
myarr

array([45,  3,  5,  6], dtype=int8)

In [8]:
myarr[3]=60

In [9]:
myarr

array([45,  3,  5, 60], dtype=int8)

In [10]:
i=89

In [11]:
i

89

# Array Creation : Conversion from other python structure

In [12]:
arr = np.array([[1,2,3],[4,5,6],[7,1,0]])


In [13]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [14]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [15]:
arr.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [16]:
arr.argmax()

np.int64(6)

In [17]:
arr.max()


np.int64(7)